# Numpy:

# What's Numpy?

NumPy (Numerical Python) is an open source Python library that's used in almost every field of science and engineeing. 

The NumPy library contains multidimensional array and matrix data structures.

In [1]:
import numpy as np
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

Difference between a Python list and a NumPy array is that, the Numpy gives you an enormous range of fast and efficient ways of creating arrays and manipulating data inside them. While a list can contain different data types within a single list, all of the elements in a NumPy array should be homogeneous.

NumPy arrays are faster and more compact than Python lists. An array consumes less memory and it is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types.This allows the code to be optimized even further.

ARRAY: An array is a central data structure of the NumPy library. It is grid of values and it contains information about the raw data. The elements are all of the same type, referred to as the array dtype. The rank of the array is the number of dimensions. The shape of the array is a tuple of integers giving the size of the array along each dimension.

In [3]:
#Example:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 8, 7, 1]])
print(a[0])

[1 2 3 4]


The NumPy ndarray class is used to represent both matrices and vectors.

Vector is an array with a single dimension (there's no difference between row and column vectors), while a matrix refers to an array with two dimensions. For 3-D or higher dimensional arrays, the term tensor is also commonly used.

In [7]:
#To create a NumPy array, you can use the function np.array()
import numpy as np
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [8]:
#Creating an array filled with 0's
np.zeros(2)

array([0., 0.])

In [9]:
#Creating an array filled with 1's
np.ones(2)

array([1., 1.])

In [10]:
#Create an empty array with 2 elements
np.empty(2)

array([1., 1.])

In [11]:
#You can create an array with a range of elements
np.arange(4)

array([0, 1, 2, 3])

In [12]:
#An array that contains a range of evenly spaced intervals. To do this you will specify the first number, last number, and the step size.
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [13]:
#To create an array with values that are spaced linearly in a specfied interval
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

While the default data type is floating point(np.float64), you can explictly specify which data type you want using the dtype keyword.

In [14]:
#Specifying your data type
x = np.ones(4, dtype=np.int64)
x

array([1, 1, 1, 1], dtype=int64)

Adding, removing, and sorting elements

In [15]:
#You can quickly sort the numbers in ascending order 
arr = np.array([2, 1, 3, 5, 7, 8, 4, 6])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])