Sorting:

In [9]:
import numpy as np
a = ([[50, 20, 40, 80], [30, 10, 35, 8]])
b = np.sort(a)#qucik sort
print(b)
np.sort(a, axis=0)#sorting with axis
d = np.dtype([('name', 'S10'),('perc', float)])#sorting with order
arr = np.array([('abhi', 54.9), ('ram', 98.9), ('bee', 55),
               ('arjun', 87.2), ('karan', 88)], dtype=d)
np.sort(arr, order='perc')


[[20 40 50 80]
 [ 8 10 30 35]]


array([(b'abhi', 54.9), (b'bee', 55. ), (b'arjun', 87.2),
       (b'karan', 88. ), (b'ram', 98.9)],
      dtype=[('name', 'S10'), ('perc', '<f8')])

In [13]:
#Argsort
import numpy as np
scores = np.array([89, 44, 79, 100, 42, 69])
players = np.array(['Jon', 'Criston', 'Ameond', 'Daemon', 'Aegon', 'Tyrion'])
print(np.sort(scores)[::-1]) #sorting high to low
print(np.argsort(scores)[::-1]) #indices of players with sorted scores 
top_3 = players[np.argsort(scores)[::-1]][:3] #Top 3 players
print(top_3)

[100  89  79  69  44  42]
[3 0 2 5 1 4]
['Daemon' 'Jon' 'Ameond']


In [16]:
#lexsort
surnames = ('Hertz', 'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')
ind = np.lexsort((first_names, surnames))
ind


array([1, 2, 0], dtype=int64)

In [18]:
[surnames[i]+","+first_names[i] for i in ind]

['Galilei,Galileo', 'Hertz,Gustav', 'Hertz,Heinrich']

In [24]:
a = [1, 5, 1, 4, 3, 4, 4]
b = [9, 4, 0, 4, 0, 2, 1]
ind = np.lexsort((b, a))
ind

array([2, 0, 4, 6, 5, 3, 1], dtype=int64)

In [22]:
[(a[i], b[i]) for i in ind]

[(1, 0), (1, 9), (3, 0), (4, 1), (4, 2), (4, 4), (5, 4)]

In [25]:
#searchsorted
np.searchsorted([1, 2, 3, 4, 5, 6], 3)

2

In [4]:
import numpy as np
np.searchsorted([2, 3, 5, 6], 1, side='right')

0

In [5]:
np.searchsorted([1, 2, 3, 4, 5], [-10, 10, 2, 3])

array([0, 5, 1, 2], dtype=int64)

In [6]:
# where() returns index of given value
a = np.arange(10, 100, 10)
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [7]:
np.where(a==30)

(array([2], dtype=int64),)

In [8]:
np.where(a%30==0)

(array([2, 5, 8], dtype=int64),)

In [14]:
# Partition function
i = np.array([3, 2, 4, 5, 1, 7, 9])
np.partition(i, 3)

array([1, 2, 3, 4, 5, 7, 9])

In [18]:
# Concatenate
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])