Sorting:

In [9]:
import numpy as np
a = ([[50, 20, 40, 80], [30, 10, 35, 8]])
b = np.sort(a)#qucik sort
print(b)
np.sort(a, axis=0)#sorting with axis
d = np.dtype([('name', 'S10'),('perc', float)])#sorting with order
arr = np.array([('abhi', 54.9), ('ram', 98.9), ('bee', 55),
               ('arjun', 87.2), ('karan', 88)], dtype=d)
np.sort(arr, order='perc')


[[20 40 50 80]
 [ 8 10 30 35]]


array([(b'abhi', 54.9), (b'bee', 55. ), (b'arjun', 87.2),
       (b'karan', 88. ), (b'ram', 98.9)],
      dtype=[('name', 'S10'), ('perc', '<f8')])

In [13]:
#Argsort
import numpy as np
scores = np.array([89, 44, 79, 100, 42, 69])
players = np.array(['Jon', 'Criston', 'Ameond', 'Daemon', 'Aegon', 'Tyrion'])
print(np.sort(scores)[::-1]) #sorting high to low
print(np.argsort(scores)[::-1]) #indices of players with sorted scores 
top_3 = players[np.argsort(scores)[::-1]][:3] #Top 3 players
print(top_3)

[100  89  79  69  44  42]
[3 0 2 5 1 4]
['Daemon' 'Jon' 'Ameond']


In [ ]:
#lexsort
