How do you know the shape and size of an array?
ndarray.ndim will tell you the no of axes, or dimensions, of the array.
ndarray.size will give total no of elements of the array. This is product of the elements of the array shape.
ndarray.shape will display a tuple of integers that indicate the no of elements stored along each dimension of the array.

In [9]:
import numpy as np
arr = np.array([[[0, 1, 2, 3], 
                 [4, 5, 6, 7]],
                 
                 [[0, 1, 2, 3],
                  [4, 5, 6, 7]],
                 
                 [[0, 1, 2, 3],
                  [4, 5, 6, 7]]])
    
                                             

In [10]:
arr.ndim

3

In [11]:
arr.size

24

In [12]:
arr.shape

(3, 2, 4)

reshape(): It will give a new shape to an array without changing the data. Note: Need to see if same no of elements are present in new array as the original array.

In [13]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [16]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [15]:
#reshape can specify a few optional parameters
np.reshape(a, newshape=(2, 3), order='C')

array([[0, 1, 2],
       [3, 4, 5]])

Converting a 1D array into a 2D array using new axis to an array.

In [17]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [18]:
#using np.newaxis to add a new axis
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [19]:
# converting on basis of row
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [21]:
#converting on bases of column
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [27]:
# Using expand_dims
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
a.shape

[1 2 3 4 5 6]


(6,)

In [26]:
# To add an axis at index position 1 with
b = np.expand_dims(a, axis=1)
print(b)
b.shape

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


(6, 1)

In [25]:
# Adding an axis at index position 0 with:
c = np.expand_dims(a, axis=0)
print(c)
c.shape

[[1 2 3 4 5 6]]


(1, 6)