Indexing and Slicing

In [1]:
import numpy as np
data = np.array([1, 2, 3])
data[1]

2

In [2]:
data[0:2]

array([1, 2])

In [3]:
data[1:]

array([2, 3])

In [4]:
data[-2:]

array([2, 3])

In [5]:
# To select values that fulfill certain conditions
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a<5])

[1 2 3 4]


In [6]:
five_up = (a>=5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [7]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [8]:
c = a[(a>2)&(a<11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [9]:
# If the output needed in boolean
five_up = (a>5) | (a==5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [10]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = np.nonzero(a<5)
print(b) # To print the indices of elements that are less than 5
# first array represents row location, second array represents column location

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [11]:
# To zip the arrays, iterate over the list of coordinates
list_coordinates = list(zip(b[0], b[1]))
for coord in list_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [13]:
print(a[b])# To print elements in an array that are less than 5

[1 2 3 4]


In [14]:
not_there = np.nonzero(a == 42)
print(not_there) # to get the elements that are not present

(array([], dtype=int64), array([], dtype=int64))


To create an array from existing data

In [15]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [16]:
a1 = np.array([[1, 1],
               [2, 2]])
a2 = np.array([[3, 3],
               [4, 4]])
# To stack arrays vertically
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [17]:
# To stack horizontally
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [18]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [19]:
# To split equally into 3 arrays
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [20]:
#To split array after third and fourth column
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [21]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [22]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [23]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
# copy method is to make a complete copy of the array and its data (a deep copy). To use this on your array, you could run
b2 = a.copy()
print(b2)

[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Basic array operations

In [26]:
#add the arrays
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [27]:
data - ones #substraction

array([0, 1])

In [28]:
data * data #multiplication

array([1, 4])

In [29]:
data / data #division

array([1., 1.])

In [30]:
# To find the sum of elements in an array
a = np.array([1, 2, 3, 4])
a.sum()

10

In [31]:
b = np.array([[1, 1], [2, 2]])
b.sum(axis=0) # sum over the axis of row

array([3, 3])

In [32]:
b.sum(axis=1) # sum over the axis of columns 

array([2, 4])